name: PHP Composer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3

    # This is what's responsible for setting the right php version
    # https://github.com/marketplace/actions/setup-php-action
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'

    - name: Validate composer.json and composer.lock
      run: ./composer.phar validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-
    - name: Install dependencies
      run: ./composer.phar install --prefer-dist --no-progress

    - name: PHPUnit
      run: ./composer.phar run-script test

    - name: PHP CodeSniffer
      run: ./composer.phar run-script phpcs

    - name: PHP Mess Detector
      run: ./composer.phar run-script phpmd

    - name: PHPStan
      run: ./composer.phar run-script phpstan
